<?php
/**
 * Spectrum Display Fields Configuration
 *
 * This file contains the field mapping configuration for displaying
 * Spectrum culture object records. This data was previously stored in
 * spectrum-display.csv and has been converted to a PHP array for
 * better performance.
 *
 * @package Culture Object MDS Display
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array( 'Field group', 'Field', '', 'Content', '' ),
	array( 'Identification', 'Object number', '', 'spectrum/object_number', '' ),
	array( '', 'Other number', '', 'spectrum/other_number', '' ),
	array( '', 'Number of objects', '', 'spectrum/number_of_objects', '' ),
	array( '', 'Object name', '', 'spectrum/object_name', '' ),
	array( '', '', 'Object name type', 'spectrum/object_name_type', '' ),
	array( '', 'Title', '', 'spectrum/title', '' ),
	array( '', 'Brief description', '', 'spectrum/brief_description', '' ),
	array( '', 'Comments', '', 'spectrum/comments', '' ),
	array( '', 'Distinguishing features', '', 'spectrum/distinguishing_features', '' ),
	array( '', 'Responsible department/section', '', 'spectrum/responsible_department_section', '' ),
	array( 'Description', 'Age', '', 'spectrum/age', '' ),
	array( '', 'Colour', '', 'spectrum/colour', '' ),
	array( '', 'Content - activity', '', 'spectrum/content_activity', '' ),
	array( '', 'Content - concept', '', 'spectrum/content_concept', '' ),
	array( '', 'Content - date', '', 'spectrum/content_date', '' ),
	array( '', 'Content - description', '', 'spectrum/content_description', '' ),
	array( '', 'Content - event name', '', 'spectrum/content_event_name', '' ),
	array( '', 'Content - language', '', 'spectrum/content_language', '' ),
	array( '', 'Content - note', '', 'spectrum/content_note', '' ),
	array( '', 'Content – object', '', 'spectrum/content_object', '' ),
	array( '', 'Content - organisation', '', 'spectrum/content_organisation', '' ),
	array( '', 'Content - other', '', 'spectrum/content_other', '' ),
	array( '', 'Content - people', '', 'spectrum/peoples_culture', '' ),
	array( '', 'Content - person', '', 'spectrum/content_person_', '' ),
	array( '', 'Content - place', '', 'spectrum/content_place', '' ),
	array( '', 'Content - position', '', 'spectrum/content_position', '' ),
	array( '', 'Content - script', '', 'spectrum/content_script', '' ),
	array( '', 'Copy number', '', 'spectrum/copy_number', '' ),
	array( '', 'Dimension', '', 'spectrum/dimension', '' ),
	array( '', '', 'Dimension measured part', 'spectrum/dimension_measured_part', '' ),
	array( '', '', 'Dimension value', 'spectrum/dimension_value', '' ),
	array( '', '', 'Dimension measurement unit', 'spectrum/dimension_measurement_unit', '' ),
	array( '', 'Edition number', '', 'spectrum/edition_number', '' ),
	array( '', 'Form', '', 'spectrum/form', '' ),
	array( '', 'Inscription content', '', 'spectrum/inscription_content', '' ),
	array( '', '', 'Inscriber', 'spectrum/inscriber', '' ),
	array( '', '', 'Inscription date', 'spectrum/inscription_date', '' ),
	array( '', '', 'Inscription description', 'spectrum/inscription_description', '' ),
	array( '', '', 'Inscription interpretation', 'spectrum/inscription_interpretation', '' ),
	array( '', '', 'Inscription language', 'spectrum/inscription_language', '' ),
	array( '', '', 'Inscription method', 'spectrum/inscription_method', '' ),
	array( '', '', 'Inscription position', 'spectrum/inscription_position', '' ),
	array( '', '', 'Inscription script', 'spectrum/inscription_script', '' ),
	array( '', '', 'Inscription translation', 'spectrum/inscription_translation', '' ),
	array( '', '', 'Inscription transliteration', 'spectrum/inscription_transliteration', '' ),
	array( '', '', 'Inscription type', 'spectrum/inscription_type', '' ),
	array( '', 'Material', '', 'spectrum/material', '' ),
	array( '', 'Object status', '', 'spectrum/object_status', '' ),
	array( '', 'Phase', '', 'spectrum/phase', '' ),
	array( '', 'Physical description', '', 'spectrum/physical_description', '' ),
	array( '', 'Sex', '', 'spectrum/sex', '' ),
	array( '', 'Style', '', 'spectrum/style', '' ),
	array( '', 'Technical attribute', '', 'spectrum/technical_attribute', '' ),
	array( '', 'Technical attribute measurement', '', 'spectrum/technical_attribute_measurement', '' ),
	array( '', 'Object component name', '', 'spectrum/object_component_name', '' ),
	array( 'Location', 'Current location', '', 'spectrum/current_location', '' ),
	array( 'Requirements', 'Display recommendations', '', 'spectrum/display_recommendations', '' ),
	array( '', 'Environmental recommendations', '', 'spectrum/environmental_recommendations', '' ),
	array( '', 'Handling recommendations', '', 'spectrum/handling_recommendations', '' ),
	array( '', 'Packing recommendations', '', 'spectrum/packing_recommendations', '' ),
	array( 'Production', 'Object production date', '', 'spectrum/object_production_date', '' ),
	array( '', 'Object production note', '', 'spectrum/object_production_note', '' ),
	array( '', 'Object production organisation', '', 'spectrum/object_production_organisation', '' ),
	array( '', 'Object production person', '', 'spectrum/object_production_person', '' ),
	array( '', 'Object production place', '', 'spectrum/object_production_place', '' ),
	array( '', 'Object production reason', '', 'spectrum/object_production_reason', '' ),
	array( '', 'Technique', '', 'spectrum/technique', '' ),
	array( 'History and association', 'Associated activity', '', 'spectrum/associated_activity', '' ),
	array( '', 'Associated concept', '', 'spectrum/associated_concept', '' ),
	array( '', 'Associated cultural affinity', '', 'spectrum/associated_cultural_affinity', '' ),
	array( '', 'Associated date', '', 'spectrum/associated_date', '' ),
	array( '', 'Associated event date', '', 'spectrum/associated_event_date', '' ),
	array( '', 'Associated event name', '', 'spectrum/associated_event_name', '' ),
	array( '', 'Associated object', '', 'spectrum/associated_object', '' ),
	array( '', 'Associated object type', '', 'spectrum/associated_object_type', '' ),
	array( '', 'Associated organisation ', '', 'spectrum/associated_organisation', '' ),
	array( '', 'Associated people ', '', 'spectrum/associated_people', '' ),
	array( '', 'Associated person ', '', 'spectrum/associated_person', '' ),
	array( '', 'Associated place ', '', 'spectrum/associated_place', '' ),
	array( '', 'Association note', '', 'spectrum/association_note', '' ),
	array( '', 'Association type', '', 'spectrum/association_type', '' ),
	array( '', 'Object history note', '', 'spectrum/object_history_note', '' ),
	array( '', 'Owner', '', 'spectrum/owner', '' ),
	array( '', 'Ownership dates', '', 'spectrum/ownership_dates', '' ),
	array( '', 'Related object number', '', 'spectrum/related_object_number', '' ),
	array( '', 'Usage', '', 'spectrum/usage', '' ),
	array( '', 'Usage note', '', 'spectrum/usage_note', '' ),
	array( 'Collection', 'Field collection date', '', 'spectrum/field_collection_date', '' ),
	array( '', 'Field collection method', '', 'spectrum/field_collection_method', '' ),
	array( '', 'Field collection note', '', 'spectrum/field_collection_note', '' ),
	array( '', 'Field collection place ', '', 'spectrum/field_collection_place', '' ),
	array( '', 'Field collection source', '', 'spectrum/field_collection_source', '' ),
	array( '', 'Field collector', '', 'spectrum/field_collector', '' ),
	array( '', 'Geological complex name', '', 'spectrum/geological_complex_name', '' ),
	array( '', 'Habitat', '', 'spectrum/habitat', '' ),
	array( '', 'Habitat note', '', 'spectrum/habitat_note', '' ),
	array( '', 'Stratigraphic unit name', '', 'spectrum/stratigraphic_unit_name', '' ),
	array( 'Rights', 'Right reference number', '', 'spectrum/right_reference_number', '' ),
	array( '', 'Right type', '', 'spectrum/right_type', '' ),
	array( '', 'Right holder', '', 'spectrum/right_holder', '' ),
	array( '', 'Right note', '', 'spectrum/right_note', '' ),
	array( 'Condition and technical assessment', 'Completeness', '', 'spectrum/completeness', '' ),
	array( '', 'Condition', '', 'spectrum/condition', '' ),
	array( 'Consevation and treatment', 'Treatment begin date', '', 'spectrum/treatment_begin_date', '' ),
	array( '', 'Treatment end date', '', 'spectrum/treatment_end_date', '' ),
	array( '', 'Conservation note', '', 'spectrum/conservation_note', '' ),
	array( 'Owner\'s contribution', 'Owner\'s personal experience', '', 'spectrum/owners_personal_experience', '' ),
	array( '', 'Owner\'s reference', '', 'spectrum/owners_reference', '' ),
	array( '', 'Owner\'s contribution note', '', 'spectrum/owners_contribution_note', '' ),
	array( 'Use', 'Credit line', '', 'spectrum/credit_line', '' ),
	array( '', 'Use status', '', 'spectrum/use_status', '' ),
	array( '', 'Text', '', 'spectrum/text', '' ),
	array( '', 'Use note', '', 'spectrum/use_note', '' ),
	array( 'User\'s contribution', 'User\'s reference', '', 'spectrum/users_reference', '' ),
	array( '', 'User\'s role', '', 'spectrum/users_role', '' ),
	array( '', 'User\'s personal experience', '', 'spectrum/users_personal_experience', '' ),
	array( '', 'User\'s contribution note', '', 'spectrum/users_contribution_note', '' ),
	array( 'Object entry', 'Entry number', '', 'spectrum/entry_number', '' ),
	array( '', 'Entry date', '', 'spectrum/entry_date', '' ),
	array( '', 'Entry method', '', 'spectrum/entry_method', '' ),
	array( '', 'Entry reason', '', 'spectrum/entry_reason', '' ),
	array( '', 'Depositor', '', 'spectrum/depositor', '' ),
	array( '', 'Entry note', '', 'spectrum/entry_note', '' ),
	array( '', 'Return date', '', 'spectrum/return_date', '' ),
	array( 'Acquisition information', 'Accession date', '', 'spectrum/accession_date', '' ),
	array( '', 'Acquisition date', '', 'spectrum/acquisition_date', '' ),
	array( '', 'Acquisition method', '', 'spectrum/acquisition_method', '' ),
	array( '', 'Acquisition note', '', 'spectrum/acquisition_note', '' ),
	array( '', 'Acquisition reference number', '', 'spectrum/acquisition_reference_number', '' ),
	array( '', 'Acquisition source', '', 'spectrum/acquisition_source', '' ),
	array( 'Condition and technical assessment (Procedural)', 'Condition check/assessment reference number', '', 'spectrum/condition_check/assessment_reference_number', '' ),
	array( '', 'Condition checker/assessor ', '', 'spectrum/condition_checker/assessor', '' ),
	array( '', 'Condition check/assessment reason', '', 'spectrum/condition_check/assessment_reason', '' ),
	array( '', 'Condition check/assessment method', '', 'spectrum/condition_check/assessment_method', '' ),
	array( '', 'Condition check/assessment note', '', 'spectrum/condition_check/assessment_note', '' ),
	array( '', 'Condition check/assessment date', '', 'spectrum/condition_check_assessment_date', '' ),
	array( 'Conservation and treatment (Procedural)', 'Conservation reference number', '', 'spectrum/conservation_reference_number', '' ),
	array( '', 'Conservation authoriser ', '', 'spectrum/conservation_authoriser', '' ),
	array( '', 'Conservation method', '', 'spectrum/conservation_method', '' ),
	array( '', 'Conservator', '', 'spectrum/conservator', '' ),
	array( 'Use (Procedural)', 'Use reference number', '', 'spectrum/use_reference_number', '' ),
	array( '', 'Use type', '', 'spectrum/use_type', '' ),
	array( '', 'Use authoriser ', '', 'spectrum/use_authoriser_', '' ),
	array( '', 'Use title', '', 'spectrum/use_title', '' ),
	array( '', 'Use begin date', '', 'spectrum/use_begin_date', '' ),
	array( '', 'Use end date', '', 'spectrum/use_end_date', '' ),
	array( '', 'User', '', 'spectrum/user', '' ),
	array( '', 'Use organiser', '', 'spectrum/use_organiser', '' ),
	array( '', 'Use venue ', '', 'spectrum/use_venue', '' ),
	array( '', 'Use result', '', 'spectrum/use_result', '' ),
	array( 'Reproduction', 'Reproduction number', '', 'spectrum/reproduction_number', '' ),
	array( '', 'Current reproduction location', '', 'spectrum/current_reproduction_location', '' ),
	array( '', 'Reproduction creator', '', 'spectrum/reproduction_creator', '' ),
	array( '', 'Reproduction date', '', 'spectrum/reproduction_date', '' ),
	array( '', 'Reproduction description', '', 'spectrum/reproduction_description', '' ),
	array( '', 'Reproduction format', '', 'spectrum/reproduction_format', '' ),
	array( '', 'Reproduction status', '', 'spectrum/reproduction_status', '' ),
	array( '', 'Reproduction type', '', 'spectrum/reproduction_type', '' ),
	array( '', 'Reproduction reason', '', 'spectrum/reproduction_reason', '' ),
);
